// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEOQpWiIcbNUvKyMUoE8BXGUjczOtLKdA',
    appId: '1:75225561632:web:f30dc2411d8ed934369a45',
    messagingSenderId: '75225561632',
    projectId: 'dailytodo-28159',
    authDomain: 'dailytodo-28159.firebaseapp.com',
    storageBucket: 'dailytodo-28159.appspot.com',
    measurementId: 'G-WGS0GRJD7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTWgHDgWeTfQE4N2-RaJJgaaQt0zJIL9w',
    appId: '1:75225561632:android:ed91afc11d798834369a45',
    messagingSenderId: '75225561632',
    projectId: 'dailytodo-28159',
    storageBucket: 'dailytodo-28159.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_NEGZ2nT4v4JGHGjO9aCwgIbThbgC5Vc',
    appId: '1:75225561632:ios:a31b72d6ccdc9660369a45',
    messagingSenderId: '75225561632',
    projectId: 'dailytodo-28159',
    storageBucket: 'dailytodo-28159.appspot.com',
    iosBundleId: 'com.example.dailyTodo',
  );
}
